### ISSUE TITLE
Inventory numbers not generating

### ISSUE THREAD

**Issue by AD-cp** [pluginsGLPI/geninventorynumber#59] opened 2022-06-23 12:05 UTC
Hi,
Just updated to 2.8.0 and I can't generate any numbers , it stays like that : MON_<#######>
Even when you click on regenerate and ovveride , it does it but the Inventory number isn't generating.

**Comment by AD-cp** [comment] 2022-06-23 12:25
I just tried to generate and here's the log in php-errors.log

`[2022-06-23 14:22:54] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /var/www/html/glpi/src/Html.php at line 6602
  Backtrace :
  ajax/fuzzysearch.php:43                            Html::fuzzySearch()
  `

I had it with the plugin disabled and regenerating it changed it to MON_<#######> once more.

**Comment by kabassanov** [comment] 2022-06-23 13:41
Hi AD-cp,

 What version did you use before?

**Comment by kabassanov** [comment] 2022-06-23 13:44
OK, I know what the problem is... There was a code modification in 2.6.0 that dropped this. I've just discovered it also. I know the right place to modify. Just need to do it :)

**Comment by kabassanov** [comment] 2022-06-24 09:30
I replaced suffixPosition variable name by maskPosition...

**Comment by cedric-anne** [comment] 2022-07-26 11:38
Fixed by #60

**Closed by cedric-anne** 2022-07-26 11:38 UTC
